# -*- coding: utf-8 -*-
"""e 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdqkI6OZCX4xRKYBjVnVZdvpLloldwUe
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread('Screenshot 2026-08-01 143552 (2).png')

# Check if image was loaded successfully
if img is None:
    print("Error: Could not load image. Please check the file name and ensure the image exists.")
else:
    # Get image size
    rows, cols = img.shape[:2]

    # Define 4 points in original image
    pts1 = np.float32([[50, 50],
                       [200, 50],
                       [50, 200],
                       [200, 200]])

    # Define new positions (warped perspective)
    pts2 = np.float32([[10, 100],
                       [200, 50],
                       [100, 250],
                       [220, 220]])

    # Compute perspective transformation matrix
    M = cv2.getPerspectiveTransform(pts1, pts2)

    # Apply transformation
    perspective = cv2.warpPerspective(img, M, (cols, rows))

    # Display images
    print("Original Image:")
    cv2_imshow(img)
    print("Perspective Transformed:")
    cv2_imshow(perspective)