# -*- coding: utf-8 -*-
"""EXP 21

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbEL9K7UaUvKnK6eAnnM2IBL1uKiEICm
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt
import numpy as np

# Read the image
# The 'image.jpg' file does not exist in the Colab environment.
# Instead, use the name of the file that was uploaded via `files.upload()`.
# The variable 'uploaded_filename' holds this name.
img = cv2.imread(uploaded_filename)

# Check if image was loaded successfully
if img is None:
    print(f"Error: Could not load image '{uploaded_filename}'. Please ensure it's a valid image file.")
else:
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Laplacian mask with diagonal neighbors
    laplacian_mask = np.array([
        [1,  1,  1],
        [1, -8,  1],
        [1,  1,  1]
    ], dtype=np.float32)

    # Apply Laplacian filter
    laplacian = cv2.filter2D(gray, cv2.CV_32F, laplacian_mask)

    # Sharpen the image
    sharpened = gray.astype(np.float32) - laplacian

    # Convert to 8-bit
    sharpened = cv2.convertScaleAbs(sharpened)

    # Display images
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(gray, cmap="gray")
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(sharpened, cmap="gray")
    plt.title("Sharpened Image")
    plt.axis("off")

    plt.show()