# -*- coding: utf-8 -*-
"""EXP_23

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGMv9bTm5C_bnQTPVPs2oMBddLxi3TyX
"""

from google.colab import files
uploaded = files.upload()

from PIL import Image, ImageFilter
import io

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

# Read the image data from the uploaded dictionary
image_data = uploaded[image_filename]
im1 = Image.open(io.BytesIO(image_data))

im2 = im1.filter(ImageFilter.UnsharpMask(radius=3, percent=200, threshold=5))

# To display the image in Colab, use display()
display(im1)
display(im2)