# -*- coding: utf-8 -*-
"""e 11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdqkI6OZCX4xRKYBjVnVZdvpLloldwUe
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread('Screenshot 2026-08-01 143552 (1).png')

# Check if image was loaded successfully
if img is None:
    print("Error: Could not load image. Please check the file name and ensure the image exists.")
else:
    rows, cols = img.shape[:2]

    # Define 3 points in original image
    pts1 = np.float32([[50, 50],
                       [200, 50],
                       [50, 200]])

    # Define new positions for these points
    pts2 = np.float32([[10, 100],
                       [200, 50],
                       [100, 250]])

    # Compute affine transformation matrix
    M = cv2.getAffineTransform(pts1, pts2)

    # Apply transformation
    affine = cv2.warpAffine(img, M, (cols, rows))

    # Display images
    print("Original Image:")
    cv2_imshow(img)
    print("Affine Transformed:")
    cv2_imshow(affine)