# -*- coding: utf-8 -*-
"""EXP 13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cW6Cj3rjn8VcHI7slHyYFLuD6EI3zvyD
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow # Import cv2_imshow for Colab

# Define points for perspective transformation
roi_points = np.array([(150, 200), (450, 200), (550, 500), (50, 500)])
target_points = np.array([(0, 0), (400, 0), (400, 600), (0, 600)])
M = cv2.getPerspectiveTransform(roi_points.astype(np.float32), target_points.astype(np.float32))

# --- Changes for Colab compatibility ---
# Instead of webcam (cv2.VideoCapture(0)), read an uploaded image.
# You had uploaded 'Screenshot 2026-08-07 133747 (3).png', using it as an example.
# Please change the filename if you want to use a different uploaded image.
img = cv2.imread("Screenshot 2026-08-07 133747 (3).png")

if img is None:
    print("Error: Could not load the image. Please check the filename and ensure it's uploaded.")
else:
    # Resize image to match the video frame size for consistent transformation, if needed
    # Or, adjust target_points and M based on img.shape
    # For this example, let's assume original image size is compatible or transformation handles it.
    # If the image dimensions are significantly different from expected (e.g., 640x480 for webcam),
    # the perspective transform might not look as intended.
    rows, cols = img.shape[:2]

    # Apply perspective transformation to the static image
    dst = cv2.warpPerspective(img, M, (cols, rows)) # Use image dimensions for warpPerspective

    # Display original and transformed images using cv2_imshow
    cv2_imshow(img)
    cv2_imshow(dst)

    # Save the transformed image
    cv2.imwrite('Perspective_Transformed_Image_Static.jpg', dst)
    print("Perspective transformed image saved as 'Perspective_Transformed_Image_Static.jpg'")

# Removed cv2.waitKey(1), cap.release(), and cv2.destroyAllWindows()
# as they are not needed with cv2_imshow and for static image processing.