# -*- coding: utf-8 -*-
"""exp 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12glIugWcg9PUoJb1Z3qZeX-UKvWVvduN
"""

from google.colab import files
uploaded = files.upload()

import cv2
from google.colab.patches import cv2_imshow # Import for Colab display

# Step 1: Read the image
# Use the filename from the uploaded file
image = cv2.imread('xtiwtP5YXNLJ8TxMPigGfqlLjLkz29fBmjZF1eF6pUAyY3inaAOg3p7aN_8_lKtRHGThgWCOacEC2TtzRKqh79__HnlPBr5pBJt3fxT5QJNdQZ7d9gATusnQYUjbv2OQ__VuB3b-ZATTBj_ESpv2vVFigSI7KuuBXgbJq71i8zs.jpg') # replace with your uploaded image path

if image is None:
    print("Error: Image not found! Please check the filename.")
    exit()

# Step 2: Resize to SMALLER size (reduce)
small_image = cv2.resize(image, None, fx=0.5, fy=0.5)   # 50% size

# Step 3: Resize to BIGGER size (enlarge)
big_image = cv2.resize(image, None, fx=2.0, fy=2.0)     # 200% size

# Step 4: Display images (using cv2_imshow for Colab compatibility)
cv2_imshow(image)
cv2_imshow(small_image)
cv2_imshow(big_image)

# cv2.waitKey(0) and cv2.destroyAllWindows() are not needed/supported in Colab for cv2_imshow

# Step 5: Save output (optional)
cv2.imwrite("small_image.jpg", small_image)
cv2.imwrite("big_image.jpg", big_image)

import cv2
from google.colab.patches import cv2_imshow # Import for Colab display

# Corrected path for Colab and removed extra parenthesis
image = cv2.imread('xtiwtP5YXNLJ8TxMPigGfqlLjLkz29fBmjZF1eF6pUAyY3inaAOg3p7aN_8_lKtRHGThgWCOacEC2TtzRKqh79__HnlPBr5pBJt3fxT5QJNdQZ7d9gATusnQYUjbv2OQ__VuB3b-ZATTBj_ESpv2vVFigSI7KuuBXgbJq71i8zs.jpg')

if image is None:
    print("Error: Image not found! Please ensure 'xtiwtP5YXNLJ8TxMPigGfqlLjLkz29fBmjZF1eF6pUAyY3inaAOg3p7aN_8_lKtRHGThgWCOacEC2TtzRKqh79__HnlPBr5pBJt3fxT5QJNdQZ7d9gATusnQYUjbv2OQ__VuB3b-ZATTBj_ESpv2vVFigSI7KuuBXgbJq71i8zs.jpg' is in your Colab files.")
    exit()

height, width = image.shape[:2]

scale_factor_bigger = 3.0
bigger_image = cv2.resize(image,(int(width*scale_factor_bigger),
int(height*scale_factor_bigger)))

scale_factor_smaller = 0.5
smaller_image = cv2.resize(image,(int(width*scale_factor_smaller),
int(height*scale_factor_smaller)))

# Using cv2_imshow for displaying images in Colab
print("Original Image:")
cv2_imshow(image)
print("Bigger Image:")
cv2_imshow(bigger_image)
print("Smaller Image:")
cv2_imshow(smaller_image)

# cv2.waitKey(0) and cv2.destroyAllWindows() are not needed/supported with cv2_imshow

cv2.imwrite("Bigger_image.jpg",bigger_image)
cv2.imwrite("smaller_image.jpg",smaller_image)