# -*- coding: utf-8 -*-
"""EXP 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KnKDjMHWr_zqlGydQneKvWNkCKemXJV
"""

from google.colab import files
uploaded = files.upload()

import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('/content/Screenshot 2026-05-07 211732.png')
blur = cv2.GaussianBlur(image, (5, 5), 10)
cv2.imwrite('blurred_image.jpg', blur)
cv2_imshow(blur)