# -*- coding: utf-8 -*-
"""EXP 18

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbEL9K7UaUvKnK6eAnnM2IBL1uKiEICm
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

# Read the image in grayscale
# The 'image.jpg' file does not exist in the Colab environment.
# Instead, use the name of the file that was uploaded via `files.upload()`.
# The variable 'uploaded_filename' holds this name.
img = cv2.imread(uploaded_filename, cv2.IMREAD_GRAYSCALE)

# Check if image was loaded successfully
if img is None:
    print(f"Error: Could not load image '{uploaded_filename}'. Please ensure it's a valid image file.")
else:
    # Apply Sobel operator along Y-axis
    sobel_y = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

    # Convert to 8-bit image
    sobel_y = cv2.convertScaleAbs(sobel_y)

    # Display original and edge-detected images
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(img, cmap="gray")
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(sobel_y, cmap="gray")
    plt.title("Sobel Y Edge Detection")
    plt.axis("off")

    plt.show()