# -*- coding: utf-8 -*-
"""EXP 14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cW6Cj3rjn8VcHI7slHyYFLuD6EI3zvyD
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Load the input image
# Fix: Changed the image path to use one of the uploaded file names.
# Please adjust "Screenshot 2026-08-07 142745.png" if you intend to use a different uploaded image.
image = cv2.imread("Screenshot 2026-08-07 142745.png")

# Check if image is loaded
if image is None:
    print("Error: Image not found! Please check the file name and ensure it's uploaded.")
    exit()

# Get image dimensions
h, w = image.shape[:2]

# Source points (corners of the original image)
src_points = np.float32([
    [0, 0],
    [w - 1, 0],
    [w - 1, h - 1],
    [0, h - 1]
])

# Destination points (modify these for perspective transformation)
dst_points = np.float32([
    [50, 50],
    [w - 100, 30],
    [w - 50, h - 50],
    [100, h - 20]
])

# Compute Homography Matrix
H, status = cv2.findHomography(src_points, dst_points)

print("Homography Matrix:")
print(H)

# Apply Perspective Transformation
transformed_image = cv2.warpPerspective(image, H, (w, h))

# Display images
# Fix: Replaced cv2.imshow with cv2_imshow for Colab compatibility.
cv2_imshow(image)
cv2_imshow(transformed_image)

# cv2.waitKey(0) and cv2.destroyAllWindows() are not needed with cv2_imshow in Colab