# -*- coding: utf-8 -*-
"""EXP 5 cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np

# Assuming 'filename' from the previously uploaded image is available in the kernel
# If not, you might need to re-upload or specify the correct file name here.
# For this example, we'll use the 'filename' variable from the kernel state if it exists.
# Otherwise, assume the uploaded file is in the /content/ directory.

# Check if 'filename' is defined in the kernel state
# if 'filename' in locals() or 'filename' in globals():
#     img_path = filename
# else:
#     # Fallback if filename is not found or directly use the name if known
#     img_path = 'Screenshot 2026-05-06 085125.png' # Replace with actual uploaded filename if different

# Given the kernel state, 'filename' is 'Screenshot 2026-05-06 085125.png'
# And it's available in the /content/ directory
img = cv2.imread('/content/' + filename)

# Add a check to ensure the image was loaded successfully
if img is None:
    raise FileNotFoundError(f"Error: Image at '/content/{filename}' could not be loaded. Please ensure the file exists.")

gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
eroded_image = cv2.erode(gray_image, kernel, iterations=1)
cv2.imwrite("eroded_image.jpg",eroded_image)

from google.colab.patches import cv2_imshow

# Convert grayscale eroded image back to BGR color
eroded_image_bgr = cv2.cvtColor(eroded_image, cv2.COLOR_GRAY2BGR)

print("Original Eroded (Grayscale) Image:")
cv2_imshow(eroded_image)

print("Eroded Image in BGR (Color) Format:")
cv2_imshow(eroded_image_bgr)