# -*- coding: utf-8 -*-
"""e 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdqkI6OZCX4xRKYBjVnVZdvpLloldwUe
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread('Screenshot 2026-08-01 143552.png')

# Check if image was loaded successfully
if img is None:
    print("Error: Could not load image. Please check the file name and ensure the image exists.")
else:
    # Get image size
    rows, cols = img.shape[:2]

    # Define translation matrix (shift right by 100, down by 50)
    M = np.float32([[1, 0, 100],
                    [0, 1, 50]])

    # Apply translation
    moved = cv2.warpAffine(img, M, (cols, rows))

    # Display images
    print("Original Image:")
    cv2_imshow(img)
    print("Moved Image:")
    cv2_imshow(moved)