# -*- coding: utf-8 -*-
"""EXP 16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tbEL9K7UaUvKnK6eAnnM2IBL1uKiEICm
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

# Read the image
# The 'image.jpg' file does not exist in the Colab environment.
# Instead, use the name of the file that was uploaded via `files.upload()`.
# The variable 'uploaded_filename' from the previous cell holds this name.
image = cv2.imread(uploaded_filename)

# Check if image was loaded successfully
if image is None:
    print(f"Error: Could not load image '{uploaded_filename}'. Please ensure it's a valid image file.")
else:
    # Convert image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply Canny edge detection
    edges = cv2.Canny(gray, 100, 200)

    # Display original and edge-detected images
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    # Convert BGR to RGB for matplotlib display
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    plt.title('Original Image')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(edges, cmap='gray')
    plt.title('Canny Edge Detection')
    plt.axis('off')

    plt.show()