# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGMv9bTm5C_bnQTPVPs2oMBddLxi3TyX
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

# Read the image from the uploaded dictionary
image_data = uploaded[image_filename]
image = cv2.imdecode(np.frombuffer(image_data, np.uint8), cv2.IMREAD_COLOR)

kernel = np.array([[0, 1, 0],
                   [1, -8, 1],
                   [0, 1, 0]])
sharpened = cv2.filter2D(image, -1, kernel)
cv2_imshow(image)
cv2_imshow(sharpened)