# -*- coding: utf-8 -*-
"""exp 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12glIugWcg9PUoJb1Z3qZeX-UKvWVvduN
"""

import cv2
from google.colab.patches import cv2_imshow
import time

# Use a VIDEO file (not image)
cap = cv2.VideoCapture('/content/video.mp4')  # upload video to Colab

# Check if opened
if not cap.isOpened():
    print("Error: Cannot open video")
    exit()

print("Playing in NORMAL speed...")
while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2_imshow(frame)
    time.sleep(0.03)   # normal speed

cap.release()

import cv2
from google.colab.patches import cv2_imshow
import time

# Assuming '/content/video.mp4' is an uploaded video file
# If you meant to process 'image1.jpg', use cv2.imread and process the single image.
cap = cv2.VideoCapture('/content/video.mp4')

if not cap.isOpened():
    print("Error: Cannot open video file. Please ensure it's uploaded to /content/video.mp4")
    exit()

slow_factor = 0.5
fast_factor = 2.0

print("Processing video...")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Resize frames for slow and fast motion
    slow_frame = cv2.resize(frame, None, fx=slow_factor, fy=slow_factor)
    fast_frame = cv2.resize(frame, None, fx=fast_factor, fy=fast_factor)

    # Use cv2_imshow for displaying in Colab
    cv2_imshow(slow_frame) # Display slow motion (you can choose which one to display)
    # cv2_imshow(fast_frame) # Uncomment to display fast motion

    # Control frame rate with time.sleep, as cv2.waitKey is not suitable
    time.sleep(0.03) # Adjust this value to control display speed

cap.release()
print("Video processing finished.")