# -*- coding: utf-8 -*-
"""EXP_24

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RGMv9bTm5C_bnQTPVPs2oMBddLxi3TyX
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

def high_boost_filter(image, boost_factor):
    # Convert image to float32 for calculations to avoid clipping
    image_float = np.float32(image)

    kernel_size = 3
    kernel = np.ones((kernel_size, kernel_size), dtype=np.float32) / (kernel_size ** 2)
    blur_image = cv2.filter2D(image_float, -1, kernel)

    # Calculate mask (high-frequency component scaled and added back)
    sharpened_float = image_float + (image_float - blur_image) * boost_factor

    # Clip values to [0, 255] and convert back to uint8
    return np.clip(sharpened_float, 0, 255).astype(np.uint8)

# Get the name of the uploaded file
image_filename = list(uploaded.keys())[0]

# Read the image data from the uploaded dictionary
image_data = uploaded[image_filename]
image = cv2.imdecode(np.frombuffer(image_data, np.uint8), cv2.IMREAD_COLOR)

sharpened_image = high_boost_filter(image, 1.5)

# Display the original and sharpened images
cv2_imshow(image)
cv2_imshow(sharpened_image)

# Optionally save the sharpened image
cv2.imwrite('sharpened_image.jpg', sharpened_image)