# -*- coding: utf-8 -*-
"""EXP 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cW6Cj3rjn8VcHI7slHyYFLuD6EI3zvyD
"""

from google.colab import files
uploaded = files.upload()

import cv2
from google.colab.patches import cv2_imshow

# Read the image
# Please change "Screenshot 2026-08-07 133747.png" to the actual uploaded image name
img = cv2.imread("Screenshot 2026-08-07 133747.png")

# Check if image is loaded
if img is None:
    print("Error: Image not found! Please check the filename.")
    # Removed exit() to allow the rest of the code to be visible if there are other issues.

# Rotate 90 degrees clockwise
clockwise = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

# Rotate 90 degrees counterclockwise
counterclockwise = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

# Display original and rotated images
cv2_imshow(img)
cv2_imshow(clockwise)
cv2_imshow(counterclockwise)

# Save rotated images
cv2.imwrite("clockwise.jpg", clockwise)
cv2.imwrite("counterclockwise.jpg", counterclockwise)

# cv2.waitKey(0) and cv2.destroyAllWindows() are not needed with cv2_imshow