# -*- coding: utf-8 -*-
"""EXP 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7CKQsuNSCFsSlcppBBApHXivcTQpQgN
"""

from collections import deque

def is_valid(m, c):
    # Check valid conditions
    if m < 0 or c < 0 or m > 3 or c > 3:
        return False
    if (m > 0 and c > m):  # Left side
        return False
    if (3 - m > 0 and 3 - c > 3 - m):  # Right side
        return False
    return True

def solve_missionaries_cannibals():
    start = (3, 3, 1)
    goal = (0, 0, 0)

    queue = deque([(start, [])])
    visited = set()

    while queue:
        (m, c, boat), path = queue.popleft()

        if (m, c, boat) in visited:
            continue

        visited.add((m, c, boat))
        path = path + [(m, c, boat)]

        if (m, c, boat) == goal:
            return path

        # Possible moves: (missionaries, cannibals)
        moves = [(1,0), (2,0), (0,1), (0,2), (1,1)]

        for move_m, move_c in moves:
            if boat == 1:  # Boat on left
                new_state = (m - move_m, c - move_c, 0)
            else:  # Boat on right
                new_state = (m + move_m, c + move_c, 1)

            if is_valid(new_state[0], new_state[1]):
                queue.append((new_state, path))

    return None


solution = solve_missionaries_cannibals()

if solution:
    print("Solution Steps:")
    for step in solution:
        print(step)
else:
    print("No solution found")