# -*- coding: utf-8 -*-
"""EXP 15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cW6Cj3rjn8VcHI7slHyYFLuD6EI3zvyD
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# Load the image
# -----------------------------
# Fix: Changed the image path to use one of the uploaded file names.
# Please adjust "Screenshot 2026-08-07 142745.png" if you intend to use a different uploaded image.
image = cv2.imread("Screenshot 2026-08-07 142745.png")

if image is None:
    print("Error: Image not found! Please check the file name and ensure it's uploaded.")
    exit()

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# -----------------------------
# Source points (Original Image)
# -----------------------------
src_pts = np.float32([
    [50, 50],
    [300, 50],
    [300, 300],
    [50, 300]
])

# -----------------------------
# Destination points (Transformed Image)
# -----------------------------
dst_pts = np.float32([
    [10, 100],
    [350, 50],
    [300, 350],
    [80, 300]
])

# -----------------------------
# Compute Homography using DLT
# -----------------------------
H, status = cv2.findHomography(src_pts, dst_pts, method=0)

print("Homography Matrix (DLT):")
print(H)

# -----------------------------
# Apply Perspective Transformation
# -----------------------------
height, width = image.shape[:2]
transformed = cv2.warpPerspective(image_rgb, H, (width, height))

# -----------------------------
# Display Results
# -----------------------------
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(transformed)
plt.title("DLT Transformed Image")
plt.axis("off")

plt.show()