# -*- coding: utf-8 -*-
"""exp 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12glIugWcg9PUoJb1Z3qZeX-UKvWVvduN
"""



import cv2
from google.colab.patches import cv2_imshow

# Step 1: Load the video file
cap = cv2.VideoCapture('video.mp4')   # replace with your video path

# Step 2: Check if video opened successfully
if not cap.isOpened():
    print("Error: Cannot open video")
    exit()

# Step 3: Read and display video frame-by-frame
while True:
    ret, frame = cap.read()

    if not ret:
        print("End of video or error")
        break

    cv2_imshow(frame)  # Changed from cv2.imshow to cv2_imshow

    # Press 'q' to exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

# Step 4: Release and close
cap.release()
cv2.destroyAllWindows()

